# Generated by Django 3.1.6 on 2021-07-23 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20210714_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='negative',
        ),
        migrations.RemoveField(
            model_name='post',
            name='positive',
        ),
        migrations.AddField(
            model_name='post',
            name='bad',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='good',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
