# Generated by Django 3.1.6 on 2021-08-10 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20210809_2122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='file',
            new_name='files',
        ),
    ]
