# Generated by Django 3.1.6 on 2021-08-15 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_auto_20210814_0756'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='post_files'),
        ),
        migrations.DeleteModel(
            name='PostFiles',
        ),
    ]
