# Generated by Django 3.1.6 on 2021-08-18 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_postfiles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='files',
        ),
        migrations.AlterField(
            model_name='postfiles',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='post_files/'),
        ),
    ]
