# Generated by Django 3.1.6 on 2021-07-24 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_channels', '0001_initial'),
        ('videos', '0003_auto_20210723_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='playlist',
            field=models.ForeignKey(blank=True, default='playlists', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='videos', to='user_channels.playlist'),
        ),
    ]
