# Generated by Django 3.1.6 on 2021-08-18 05:32

from django.db import migrations, models
import django.db.models.deletion
import froala_editor.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_channels', '0003_auto_20210809_2043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('thumbnail', models.ImageField(upload_to='')),
                ('content', froala_editor.fields.FroalaField()),
                ('licence', models.CharField(choices=[('U', 'Universal'), ('S', 'Universal/Adult'), ('A', 'Adult'), ('X', 'XXX-Content')], max_length=1)),
                ('date_uploaded', models.DateField(auto_now_add=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('good', models.PositiveBigIntegerField(default=0)),
                ('bad', models.PositiveBigIntegerField(default=0)),
                ('views', models.PositiveBigIntegerField(default=0)),
                ('playlist', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='blogs', to='user_channels.playlist')),
            ],
        ),
    ]
