# Generated by Django 3.2.7 on 2021-09-13 11:54

from django.db import migrations, models
import froala_editor.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('thumbnail', models.ImageField(upload_to='blog_thumbnails/')),
                ('content', froala_editor.fields.FroalaField()),
                ('licence', models.CharField(choices=[('U', 'Universal'), ('S', 'Universal/Adult'), ('A', 'Adult'), ('X', 'XXX-Content')], max_length=1)),
                ('date_uploaded', models.DateField(auto_now_add=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('good', models.PositiveBigIntegerField(default=0)),
                ('bad', models.PositiveBigIntegerField(default=0)),
                ('views', models.PositiveBigIntegerField(default=0)),
            ],
        ),
    ]
