# Generated by Django 3.1.6 on 2021-07-23 05:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='url',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
