# Generated by Django 3.1.6 on 2021-07-23 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0002_channel_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='subscribers',
            field=models.BigIntegerField(default=0),
        ),
    ]
