# Generated by Django 3.1.6 on 2021-07-23 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0003_channel_subscribers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channel',
            old_name='url',
            new_name='uuid',
        ),
    ]
