# Generated by Django 3.1.6 on 2021-07-24 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_auto_20210724_0616'),
        ('features', '0004_auto_20210723_0947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='channel',
        ),
        migrations.DeleteModel(
            name='Channel',
        ),
        migrations.DeleteModel(
            name='Playlist',
        ),
    ]
