# Generated by Django 3.1.6 on 2021-08-09 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_channels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='channel_photo',
            field=models.ImageField(default="{% static 'images/fav.png' %}", upload_to='channel_photo'),
        ),
    ]
