# Generated by Django 3.1.6 on 2021-08-09 20:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_channels', '0002_auto_20210809_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='channel_cover_photo',
            field=models.ImageField(default=None, upload_to='channel_cover_photo'),
        ),
        migrations.AddField(
            model_name='channel',
            name='date_created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
