# Generated by Django 3.1.6 on 2021-08-19 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_channels', '0003_auto_20210809_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='channel_photo',
            field=models.ImageField(upload_to='channel_photo'),
        ),
    ]
